package com.lastmiletracker.payment.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class VerifyPaymentRequest {

    @Schema(description = "Internal Order ID reference", example = "10")
    private Long orderId;

    @Schema(description = "Razorpay-generated Order ID used during checkout", example = "order_O8x9Hn2hK9n3L1")
    private String razorpayOrderId;

    @Schema(description = "Razorpay-generated Payment ID representing captured funds", example = "pay_P9n1Hw8hL9z1")
    private String razorpayPaymentId;

    @Schema(description = "HMAC-SHA256 signature generated by checkout client", example = "abcd1234efgh5678...")
    private String razorpaySignature;

    @Schema(description = "Details of the shipment to create after successful payment verification")
    private com.lastmiletracker.order.dto.OrderRequest orderDetails;
}
